- name: 创建文件夹
  file:
   path: /data
   state: directory

- name: 拷贝es包到主机
  copy: src={{ es_var }} dest={{ source_dir }}

- name: 解压es包
  command: chdir={{ source_dir }} /bin/tar xzf {{ es_var }}
 
- name: 目录重命名
  shell: "if [ ! -d {{ es_dir }} ]; then mv {{ source_dir }}/elasticsearch-7.1.1/ {{ es_dir }}; fi"

- name: 配置监听网络地址
  lineinfile:
   destfile: /data/es/config/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 0.0.0.0'
                                
- name: 开启监听端口
  lineinfile:
   destfile: /data/es/config/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'
                                         
- name: 设置node name
  lineinfile:
   destfile: /data/es/config/elasticsearch.yml
   regexp: 'node.name:'
   line: 'node.name: node-1'

- name: 拷贝启动脚本1
  template: src=es dest=/usr/bin/ owner=root group=root mode=0755

- name: 拷贝启动脚本2
  template: src=es dest=/etc/init.d owner=root group=root mode=0755

- name: 启动Elasticsearch
  shell: /usr/bin/es start

- name: 删除压缩包
  shell: rm -f {{ source_dir }}/{{ es_var }}
