- name: 拷贝kibana压缩包
  copy: src={{ kibana_package }} dest={{ source_dir }}

- name: 解压kibana包
  command: chdir={{ source_dir }} /bin/tar xzf {{ kibana_package }}

- name: 目录重命名
  shell: "if [ ! -d {{ kibana_dir }} ]; then mv {{ source_dir }}/kibana-5.2.0-linux-x86_64/ {{ kibana_dir }}; fi"

- name: 加入环境变量_1
  lineinfile:
    dest: "{{ kibana_dir }}/config/kibana.yml"
    insertbefore: "server.port:"
    line: "server.port: 5601"

- name: 加入环境变量_2
  lineinfile:
    dest: "{{ kibana_dir }}/config/kibana.yml"
    insertbefore: "server.host:"
    line: "server.host: '0.0.0.0'"
   
- name: 加入环境变量_3
  lineinfile:
    dest: "{{ kibana_dir }}/config/kibana.yml"
    insertbefore: "elasticsearch.url:"
    line: "elasticsearch.url: 'http://192.168.253.53:9200'"

- name: 加入环境变量_4
  lineinfile:
    dest: "{{ kibana_dir }}/config/kibana.yml"
    insertbefore: "kibana.index"
    line: "kibana.index: '.kibana'"

- name: 启动kibana
  shell: nohup /data/kibana/bin/kibana >> /data/kibana/kibana.nohup &
