- name: copy jdk software
  copy: src={{ jdk_package_name }} dest=/tmp/ owner=root group=root
- name: uncompression jdk software
  shell: tar -zxf /tmp/{{ jdk_package_name }} -C /usr/local
- name: 拷贝环境变量jdk_PATH
  template: src=jdk_PATH dest=/tmp owner=root group=root
- name: 加入环境变量jdk_PATH
  shell: "if [ `grep /usr/local/jdk1.8.0_161/bin /etc/profile |wc -l` -eq 0 ]; then cat /tmp/jdk_PATH >> /etc/profile && source /etc/profile; fi"
- name: delete jdk compressin files
  shell: rm -f /tmp/{{ jdk_package_name }}
