- name: 拷贝 logstash software
  copy: src={{ logstash_package }} dest={{ source_dir }}

- name: 解压 logstash software
  command: chdir={{ source_dir }} /bin/tar xf {{ logstash_package }}

- name: 目录重命名
  shell: "if [ ! -d {{ logstash_dir }} ]; then mv {{ source_dir }}/logstash-5.2.0/ {{ logstash_dir }}; fi"

- name: 删除压缩包
  shell: rm -f {{ source_dir }}/{{ logstash_package }}
 
- name: 创建配置文件目录
  file: dest={{ logstash_dir }}/conf.d mode=0755 state=directory

- name: 拷贝logstash启动脚本
  template: src=start.sh dest={{ logstash_dir }}/ owner=es group=es mode=0755


- name: change owner and group
  file: path={{ logstash_dir }} owner=es group=es


- name: 删除压缩包
  shell: rm -f {{ source_dir }}/{{ logstash_package }}
